### ISSUE TITLE
helpers.py

### ISSUE THREAD

**Issue by mnfienen** [pypest/pyemu_pestpp_workflow#1]
looks like a standalone version of `helpers.py` needs to be tracked in the repo. Same from `pyemu`?

**Comment by jwhite-usgs** [comment]
that’s the helpers in pyemu autotest - it’s just some rando functions that are used for pre and post processing.  Not needed for this unless you wanna have some extras?

**Comment by mnfienen** [comment]
but throws an error here:
```

# this simply adds that helper function to the forward run process.  The None arg says
# dont actually add a call to this function yet
pf.add_py_function("helpers.py", "replace_time_with_datetime(csv_file)", is_pre_cmd=None)
```

**Comment by jwhite-usgs** [comment]
I think we can go with out that but unless we want to have datetime in the obs names?

**Comment by mnfienen** [comment]
I think it's worth adding it but maybe just say in the block that it's optional. As it is now, though, the notebook bombs there.

**Comment by jwhite-usgs** [comment]
All good.  I’ll add that it

**Comment by mnfienen** [comment]
kewl
