### ISSUE TITLE
module 'pyemu.utils.helpers' has no attribute 'SpatialReference

### ISSUE THREAD

**Issue by SaeedTork** [pypest/pyemu_pestpp_workflow#4]
Hi 
I get this error message when I execute this:
sr = pyemu.helpers. SpatialReference.attribs_from_namfile_header(
        os.path.join(tmp_model_ws, "freyberg6.nam"),
        delr=m.dis.delr.array, delc=m.dis.delc.array)
sr
\Erro:
module 'pyemu.utils.helpers' has no attribute 'SpatialReference
Cheers

**Comment by jtwhite79** [comment]
Sorry for the delay.  I think you are using an older version of pyEMU - the latest release is 1.0.0 on pip.  Also, we are planning to add version of pyEMU, FloPy, PEST++ and MF6 to this repo soon so that there will be consistent versions of them.

**Comment by SaeedTork** [comment]
Thanks Jeremy, That was the issue. Cheers
